[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "tests"
implicit_reexport = true

[tool.bandit]
exclude_dirs = [
    "tests",
]
