[tox]
isolated_build = True
envlist = py310,py311,py312,py313,lint,bandit,mypy

[gh-actions]
python =
    3.10: py310
    3.11: py311,lint,bandit,mypy
    3.12: py312
    3.13: py313

[testenv]
deps =
    pytest>=2.8.0
commands = py.test

[testenv:lint]
basepython = python3.11
deps =
    flake8
commands = flake8 src/ tests/

[testenv:mypy]
basepython = python3.11
deps =
    mypy
    pytest>=7
commands = mypy src tests

[testenv:bandit]
basepython = python3.11
deps =
    bandit[toml]
commands = bandit -c pyproject.toml -r src/
